environ = {
    "OCIO": r"G:/Pipeline/ocio/spi-anim/config.ocio",
    "MAYA_MODULE_PATH": r"C:/pipeline_modules/maya/ornatrix;C:/pipeline_modules/maya/assetInfo;C:/pipeline_modules/maya/python_icon;C:/pipeline_modules/maya/IconTools;C:/pipeline_modules/maya/pyIconTools;C:/pipeline_modules/maya/AnimSchoolPicker;C:/pipeline_modules/maya/shard_matrix;C:/pipeline_modules/solidangle/mtoa;C:/pipeline_modules/maya/ngSkinTools;C:/Program Files/Autodesk/Maya2019/modules;C:/Users/paxtong/Documents/maya/2019/modules;C:/Users/paxtong/Documents/maya/modules;C:/Program Files/Common Files/Autodesk Shared/Modules/maya/2019",
    "MAYA_CONTENT_PATH": r"C:/Program Files/Autodesk/Maya2019/Examples;C:/Program Files/Autodesk/Bifrost/Maya2019/bifrost/examples/Bifrost_Fluids;C:/Program Files/Autodesk/Maya2019/plug-ins/MASH/MASH Examples;C:/Program Files/Autodesk/Maya2019/plug-ins/MASH/Smart Presets",
    "TT_STATUS": r"ip",
    "PYTHONDONTWRITEBYTECODE": r"TRUE",
    "MAYA_RENDER_DESC_PATH": r";C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/",
    "ORNATRIXMAYA_LICENSE_SERVER_IP": r"ornatrix.icon.local",
    "ATF_LOCATION": r"C:/Program Files/Autodesk/Maya2019/plug-ins/ATF/",
    "SERVER_BASE": r"Y:/",
    "RENDERMAN_SCRIPT_PATH": r"Z:/pipeline/pixar/RenderManStudio-19.0-maya2015/scripts",
    "PIPE2_BASE": r"G:\Pipeline\pipeline",
    "EMAIL": r"paxton@iconcreativestudio.com",
    "PIPE_ROOT": r"G:/Pipeline/.pipeline",
    "TT_FILENAME": r"Y:/RCL\assets\type\Character\Tac\work\rig\Maya\paxtong\Tac_rig_v0000.0000.ma",
    "TT_ENTID": r"15334",
    "ARC_RMS_SHADER_ROOT": r"Z:\pipeline\config\EAV\custom\config\renderman\shaders",
    "SERVER_ROOT": r"\\ICONPRFS01\Projects",
    "J_PATH": r"\\iconprfs01\Projects2\EAV",
    "QT_MAC_DONT_OVERRIDE_CTRL_LMB": r"1",
    "WORKON_HOME": r"D:/envs/.virtual/",
    "COAT_FSERVER": r"saturn:8888",
    "COMSPEC": r"C:\Windows\system32\cmd.exe",
    "TT_CREATE": r"False",
    "WINDIR": r"C:\Windows",
    "PYTHONPATH": r"D:/Pipeline/paxtong/dev/git_repo/pipeline_monolith/maya/scripts;D:/Pipeline/paxtong/dev/git_repo/pipeline_monolith/studiolibrary/2.2.6;Z:/pipeline/pixar/RenderManStudio-19.0-maya2015/scripts;Z:/pipeline/pixar/RenderManProServer-19.0/lib;Z:/pipeline/pixar/RenderManProServer-19.0/bin;D:/Pipeline/paxtong/dev/git_repo/pipeline_monolith;D:/Pipeline/paxtong/dev/git_repo/pipeline_monolith/python;D:/Pipeline/paxtong/dev/git_repo/pipeline_monolith/config;D:/Pipeline/paxtong/dev/git_repo/pipeline_monolith/python/control_tower/v0002;D:/Pipeline/paxtong/dev/git_repo/pipeline_monolith/python/control_tower;C:/Program Files/Autodesk/Maya2019/plug-ins/ATF/scripts;C:/pipeline_modules/maya/AnimSchoolPicker/1.0/2019/scripts;C:/Program Files/Autodesk/Bifrost/Maya2019/bifrost/scripts;C:/pipeline_modules/maya/IconTools/1.1/2019/scripts;C:/Program Files/Autodesk/Maya2019/plug-ins/MASH/scripts;C:/pipeline_modules/maya/ornatrix/2.4.4.20888/scripts/Autoload/AETemplates;C:/pipeline_modules/maya/ornatrix/2.4.4.20888/scripts/Autoload/Others;C:/pipeline_modules/maya/ornatrix/2.4.4.20888/scripts/Autoload/Stack;C:/pipeline_modules/maya/ornatrix/2.4.4.20888/scripts/Autoload;C:/pipeline_modules/maya/assetInfo/1.1/20XX/scripts;C:/Program Files/Autodesk/Maya2019/plug-ins/fbx/scripts;C:/pipeline_modules/maya/python_icon/1.0/20XX/scripts;C:/Program Files/Autodesk/Maya2019/plug-ins/camd/scripts;C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/scripts;C:/pipeline_modules/maya/ngSkinTools/1.7.9/scripts;C:/pipeline_modules/maya/pyIconTools/1.0/20XX/scripts;C:/pipeline_modules/maya/shard_matrix/1.0/20XX/scripts;C:/Allegorithmic/SubstanceMaya/2019/scripts;C:/Program Files/Autodesk/Bifrost/Maya2019/vnn/scripts;C:/Program Files/Autodesk/Maya2019/plug-ins/xgen/scripts;C:/pipeline_modules/maya/ornatrix/2.4.4.20888/scripts/Python;",
    "ORNATRIX_ARNOLD_PROCEDURAL_PATH": r"C:/pipeline_modules/maya/ornatrix/2.4.4.20888/2019/procedurals/OrnatrixProcedural.dll",
    "TT_TASKID": r"1045128",
    "MAYA_REVERSE_FILEFORMAT_EXT": r"1",
    "MAYA_PRESET_PATH": r";C:/Program Files/Autodesk/Maya2019/plug-ins/ATF/presets;C:/pipeline_modules/maya/AnimSchoolPicker/1.0/2019/presets;C:/Program Files/Autodesk/Bifrost/Maya2019/bifrost/presets;C:/pipeline_modules/maya/IconTools/1.1/2019/presets;C:/Program Files/Autodesk/Maya2019/plug-ins/MASH/presets;C:/pipeline_modules/maya/ornatrix/2.4.4.20888/presets;C:/pipeline_modules/maya/assetInfo/1.1/20XX/presets;C:/Program Files/Autodesk/Maya2019/plug-ins/fbx/presets;C:/pipeline_modules/maya/python_icon/1.0/20XX/presets;C:/Program Files/Autodesk/Maya2019/plug-ins/camd/presets;C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/presets;C:/pipeline_modules/maya/ngSkinTools/1.7.9/presets;C:/pipeline_modules/maya/pyIconTools/1.0/20XX/presets;C:/pipeline_modules/maya/shard_matrix/1.0/20XX/presets;C:/Allegorithmic/SubstanceMaya/2019/presets;C:/Program Files/Autodesk/Bifrost/Maya2019/vnn/presets;C:/Program Files/Autodesk/Maya2019/plug-ins/xgen/presets",
    "FBX_LOCATION": r"C:/Program Files/Autodesk/Maya2019/plug-ins/fbx/",
    "SUBSTANCE_PAINTER_2_LICENSE": r"\\iconprfs01\departments\IT\Software\Allegorithmic\license-Substance Painter 2.key",
    "PEREGRINEL_LICENSE": r"50700@iconprfs02",
    "NUKE_PATH": r"Z:\pipeline\nuke",
    "COMMONPROGRAMFILES": r"C:\Program Files\Common Files",
    "HOMEDRIVE": r"H:",
    "SYSTEMDRIVE": r"C:",
    "RVL_SERVER": r"ICONPRFS02",
    "SUBSTANCE_PAINTER_LICENSE": r"G:\IT\Software\Allegorithmic\New Keys\license-Substance Painter.key",
    "PROCESSOR_LEVEL": r"6",
    "TT_USERGROUPS": r"Leads Rigging",
    "OS": r"Windows_NT",
    "MAYA_CM_DISABLE_ERROR_POPUPS": r"1",
    "MARI_SCRIPT_PATH": r"\\iconprfs01\home$\paxtong\.mari\scripts",
    "TT_FRAMERANGE": r"1001-1096",
    "FOUNDRY_LICENSE": r"30031@iconprfs02",
    "USER": r"paxtong",
    "SYSTEMROOT": r"C:\Windows",
    "PIPE_DEV_MODE": r"TRUE",
    "MAYA_SCRIPT_BASE": r"C:/Program Files/Autodesk/Maya2019",
    "RMS_SCRIPT_PATHS": r"Z:\pipeline\config\EAV\custom\config\renderman\etc",
    "TT_MAYAFILETYPE": r"mayaAscii",
    "RENDER_DESC": r";C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/",
    "TEMP": r"C:\Users\paxtong\AppData\Local\Temp",
    "COMMONPROGRAMFILES(X86)": r"C:\Program Files (x86)\Common Files",
    "PROGRAMDATA": r"C:\ProgramData",
    "%MAYA_LOCATION%": r"C:\Program Files\Autodesk\Maya2019",
    "TT_STEPCODE": r"rig",
    "NEXTLIMIT_LICENSE": r"5060@iconprfs02",
    "FN_NUKE_DISABLE_TMPLIC_NOTIFY_DIALOG": r"1",
    "TASKTOOL_AID": r"ICONCreative.Pipeline.TaskTool",
    "QT_HARFBUZZ": r"old",
    "ORNATRIX_VERSION": r"2.4.4.20888",
    "LOGONSERVER": r"\\ICONPRFS02",
    "LOCALAPPDATA": r"C:\Users\paxtong\AppData\Local",
    "MAYA_MODULE_UI_WORKSPACE_PATH": r";C:/Program Files/Autodesk/Bifrost/Maya2019/bifrost/resources/workspaces",
    "RENDER_SCRIPT": r"D:/Pipeline/paxtong/dev/git_repo/pipeline_monolith/maya/scripts;C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/scripts",
    "QX_FLOATING_IP": r"ICONPRFS02",
    "HOMESHARE": r"\\iconprfs01\home$\paxtong",
    "TT_USERID": r"750",
    "MAYA_FBX_PLUGIN_LOCATION": r"C:/Program Files/Autodesk/Maya2019/plug-ins/fbx/plug-ins",
    "TMPDIR": r"C:/Users/paxtong/AppData/Local/Temp",
    "CLIENTNAME": r"DESKTOP-5SDJOOH",
    "DEADLINE_PATH": r"C:\Program Files\Thinkbox\Deadline9\bin",
    "ARC_DISABLE_RMS_LINEARIZE": r"1",
    "MAYA_PLUG_IN_PATH": r"Z:/pipeline/pixar/RenderManStudio-19.0-maya2015/plug-ins;Z:/pipeline/config/EAV/custom/plugins;C:/Users/paxtong/Documents/maya/2019/plug-ins;C:/Users/paxtong/Documents/maya/plug-ins;C:/Program Files/Autodesk/Maya2019/bin/plug-ins;C:/Program Files/Autodesk/Maya2019/plug-ins/ATF/plug-ins;C:/pipeline_modules/maya/AnimSchoolPicker/1.0/2019/plug-ins;C:/Program Files/Autodesk/Bifrost/Maya2019/bifrost/plug-ins;C:/pipeline_modules/maya/IconTools/1.1/2019/plug-ins;C:/Program Files/Autodesk/Maya2019/plug-ins/MASH/plug-ins;C:/pipeline_modules/maya/ornatrix/2.4.4.20888/2019;C:/pipeline_modules/maya/assetInfo/1.1/20XX/plug-ins;C:/Program Files/Autodesk/Maya2019/plug-ins/fbx/plug-ins;C:/pipeline_modules/maya/python_icon/1.0/20XX/plug-ins;C:/Program Files/Autodesk/Maya2019/plug-ins/camd/plug-ins;C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/plug-ins;C:/pipeline_modules/maya/ngSkinTools/1.7.9/plug-ins/2019;C:/pipeline_modules/maya/pyIconTools/1.0/20XX/plug-ins;C:/pipeline_modules/maya/shard_matrix/1.0/20XX/plug-ins;C:/Allegorithmic/SubstanceMaya/2019/plug-ins;C:/Program Files/Autodesk/Bifrost/Maya2019/vnn/plug-ins;C:/Program Files/Autodesk/Maya2019/plug-ins/xgen/plug-ins",
    "TT_PROJNAME": r"Rocket Club",
    "PYTHONHOME": r"C:/Program Files/Autodesk/Maya2019/Python",
    "PUBLIC": r"C:\Users\Public",
    "DEPT_BASE": r"\\iconprfs01\departments",
    "SOLIDANGLE_LICENSE": r"5059@iconprfs02",
    "REFTOOLS_VERSION": r"v0002",
    "XGEN_LOCATION": r"C:/Program Files/Autodesk/Maya2019/plug-ins/xgen/",
    "TMP": r"C:\Users\paxtong\AppData\Local\Temp",
    "PIPE_PROD": r"G:/Pipeline/pipeline",
    "COMPUTERNAME": r"ICON347",
    "USERDOMAIN": r"ICON",
    "BIFROST_LIB_CONFIG_FILES": r";C:/Program Files/Autodesk/Bifrost/Maya2019/bifrost/resources/plugin_config.json",
    "TT_ENTNAME": r"Tac",
    "RENDER_ICON": r";C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/icons",
    "SUBSTANCES_LOCATION": r"C:/Allegorithmic/SubstanceMaya/2019/substances",
    "HOME": r"C:/Users/paxtong/Documents",
    "MAYA_TOOLCLIPS_PATH": r";C:/Program Files/Autodesk/Bifrost/Maya2019/bifrost/resources/toolclips",
    "MASH_LOCATION": r"C:/Program Files/Autodesk/Maya2019/plug-ins/MASH/",
    "NUKE_TEMP_DIR": r"D:/Temp/nuke",
    "TT_ASSETS": r"",
    "TT_PROJCODE": r"RCL",
    "BIFROST_LOCATION": r"C:/Program Files/Autodesk/Bifrost/Maya2019/bifrost/",
    "TASKTOOL_VERSION": r"V00012",
    "ARC_RMS_CONFIG": r"Z:\pipeline\config\EAV\custom\config",
    "PROCESSOR_ARCHITECTURE": r"AMD64",
    "ALLUSERSPROFILE": r"C:\ProgramData",
    "MAYA_COLOR_MGT_NO_LOGGING": r"1",
    "TT_TASKNAME": r"Rigging",
    "USERDOMAIN_ROAMINGPROFILE": r"ICON",
    "ARNOLD_PLUGIN_PATH": r";C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/shaders;C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/procedurals;C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/../shaders/bin;C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/shaders;C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/procedurals",
    "PYTHONUSERBASE": r"G:/Pipeline/pipeline_external",
    "GENARTS_LICENSE": r"1060@iconprfs02",
    "USERNAME": r"paxtong",
    "TT_PLUGINS": r"False",
    "PROMPT": r"$P$G",
    "PIPE_LEGACY": r"Z:/pipeline",
    "ORNATRIX_GROOMS_DIR": r"\\iconprfs01\departments/Modeling/Grooming/ornatrix/presets/Grooms",
    "MAYA_VERSION": r"2019",
    "RMANTREE": r"Z:\pipeline\pixar\RenderManProServer-19.0",
    "TT_ENTTYPE": r"Asset",
    "RENDERMAN_MODULE_PATH": r"Z:/pipeline/pixar/RenderManStudio-19.0-maya2015/etc",
    "APP_PYTHON": r"D:/Pipeline/paxtong/dev/git_repo/pipeline_monolith/maya/scripts;D:/Pipeline/paxtong/dev/git_repo/pipeline_monolith/studiolibrary/2.2.6",
    "ARNOLD_VERSION": r"3.3.0.2",
    "TT_TIMEOFDAY": r"",
    "AL_NGSKINTOOLS_VERSION": r"1.7.9",
    "RMSTREE": r"Z:/pipeline/pixar/RenderManStudio-19.0-maya2015",
    "PATHEXT": r".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC",
    "ARNOLD_LICENSE_ATTEMPTS": r"60",
    "RENDERMAN_PLUGIN_PATH": r"Z:/pipeline/pixar/RenderManStudio-19.0-maya2015/plug-ins",
    "APPDATA": r"C:\Users\paxtong\AppData\Roaming",
    "TT_ALTNAME": r"None",
    "SUBSTANCE_DESIGNER_LICENSE": r"G:\IT\Software\Allegorithmic\New Keys\license-Substance Designer.key",
    "ORNATRIX_PRESET_DIR": r"\\iconprfs01\departments/Modeling/Grooming/ornatrix/presets/CurvePresets",
    "MTOA_PATH": r"C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/",
    "NUMBER_OF_PROCESSORS": r"12",
    "PERSONAL_SCRIPTS": r"C:\Users\paxtong\Documents\maya\scripts",
    "PROGRAMW6432": r"C:\Program Files",
    "WF_IMF_CIN_CORRECTION": r"both",
    "USERPROFILE": r"C:\Users\paxtong",
    "TT_PROJID": r"252",
    "PSMODULEPATH": r"C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules",
    "PIPE_PYTHONSITEPATH": r"D:/Pipeline/paxtong/dev/git_repo",
    "SUBSTANCE_DESIGNER_6_LICENSE": r"\\iconprfs01\departments\IT\Software\Allegorithmic\license-Substance Designer 6.key",
    "RDIR": r"Z:\pipeline\config\EAV\custom\config\renderman\etc",
    "VNN_PLUGIN_LOCATION": r"C:/Program Files/Autodesk/Bifrost/Maya2019/vnn/",
    "PROCESSOR_IDENTIFIER": r"Intel64 Family 6 Model 158 Stepping 10, GenuineIntel",
    "PROGRAMFILES": r"C:\Program Files",
    "PROCESSOR_REVISION": r"9e0a",
    "PATH": r"C:/Program Files/Autodesk/Maya2019/plug-ins/ATF/ATF;C:/Program Files/Autodesk/Maya2019/plug-ins/ATF/ATF/alias;C:/Program Files/Autodesk/Maya2019/bin/Cg;C:/Program Files/Autodesk/Maya2019/bin;/bin;C:/Windows/system32;C:/Windows;C:/Windows/System32/Wbem;C:/Windows/System32/WindowsPowerShell/v1.0/;C:/Program Files (x86)/QuickTime/QTSystem/;C:/Systems;C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common;C:/Python27;C:/Python27/Scripts;C:/Users/paxtong/AppData/Local/Microsoft/WindowsApps;C:/Users/paxtong/AppData/Local/Programs/Git/cmd;C:/Program Files/Autodesk/Bifrost/Maya2019/bifrost/bin;C:/Program Files/Autodesk/Maya2019/plug-ins/MASH/bin;C:/pipeline_modules/maya/ornatrix/2.4.4.20888/bin;C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/bin;C:/Allegorithmic/SubstanceMaya/2019/bin;C:/Program Files/Autodesk/Bifrost/Maya2019/vnn/bin;C:/Program Files/Autodesk/Maya2019/plug-ins/xgen/bin",
    "PROGRAMFILES(X86)": r"C:\Program Files (x86)",
    "PIPE_BETA": r"G:/Pipeline/pipeline_beta",
    "TT_RENDERER": r"Arnold",
    "MTOA_TEMPLATES_PATH": r";C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/../shaders/ae;C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/scripts/mtoa/ui/ae",
    "WF_IMF_CIN_WHITE_POINT": r"685",
    "ARNOLD_LICENSE_ATTEMPT_DELAY": r"5",
    "RENDER_PATH": r";C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/bin",
    "PIPE_DEV_REPO": r"D:/Pipeline/paxtong/dev/git_repo",
    "RENDER_PLUGIN": r";C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/plug-ins",
    "MTOA_EXTENSIONS_PATH": r";C:/pipeline_modules/maya/ornatrix/2.4.4.20888/2019/extensions;C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/extensions;C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/extensions",
    "TT_SGTAGS": r"[{'type': 'Tag', 'id': 2217, 'name': 'RCL_101'}, {'type': 'Tag', 'id': 2484, 'name': 'RCL_101A'}, {'type': 'Tag', 'id': 2216, 'name': 'RCL_S1'}]",
    "MAYA_SCRIPT_PATH": r"Y:/RCL/assets/type/Character/Tac/work/rig/Maya/paxtong/scripts;Z:/pipeline/pixar/RenderManStudio-19.0-maya2015/scripts;C:/Users/paxtong/Documents/maya/2019/scripts;C:/Users/paxtong/Documents/maya/scripts;C:/Users/paxtong/Documents/maya/2019/presets;D:/Pipeline/paxtong/dev/git_repo/pipeline_monolith/maya/shelves;C:/Users/paxtong/Documents/maya/2019/prefs/shelves;C:/Users/paxtong/Documents/maya/2019/prefs/markingMenus;C:/Users/paxtong/Documents/maya/2019/prefs/scripts;C:/Program Files/Autodesk/Maya2019/scripts;C:/Program Files/Autodesk/Maya2019/scripts/startup;C:/Program Files/Autodesk/Maya2019/scripts/shelves;C:/Program Files/Autodesk/Maya2019/scripts/others;C:/Program Files/Autodesk/Maya2019/scripts/AETemplates;C:/Program Files/Autodesk/Maya2019/scripts/unsupported;C:/Program Files/Autodesk/Maya2019/scripts/paintEffects;C:/Program Files/Autodesk/Maya2019/scripts/fluidEffects;C:/Program Files/Autodesk/Maya2019/scripts/hair;C:/Program Files/Autodesk/Maya2019/scripts/cloth;C:/Program Files/Autodesk/Maya2019/scripts/live;C:/Program Files/Autodesk/Maya2019/scripts/fur;C:/Program Files/Autodesk/Maya2019/scripts/muscle;C:/Program Files/Autodesk/Maya2019/scripts/turtle;C:/Program Files/Autodesk/Maya2019/scripts/FBX;C:/Program Files/Autodesk/Maya2019/scripts/mayaHIK;C:/Program Files/Autodesk/Maya2019/plug-ins/ATF/scripts;C:/pipeline_modules/maya/AnimSchoolPicker/1.0/2019/scripts;C:/Program Files/Autodesk/Bifrost/Maya2019/bifrost/scripts;C:/pipeline_modules/maya/IconTools/1.1/2019/scripts;C:/Program Files/Autodesk/Maya2019/plug-ins/MASH/scripts;C:/pipeline_modules/maya/ornatrix/2.4.4.20888/scripts/Autoload/AETemplates;C:/pipeline_modules/maya/ornatrix/2.4.4.20888/scripts/Autoload/Others;C:/pipeline_modules/maya/ornatrix/2.4.4.20888/scripts/Autoload/Stack;C:/pipeline_modules/maya/ornatrix/2.4.4.20888/scripts/Autoload;C:/pipeline_modules/maya/assetInfo/1.1/20XX/scripts;C:/Program Files/Autodesk/Maya2019/plug-ins/fbx/scripts;C:/pipeline_modules/maya/python_icon/1.0/20XX/scripts;C:/Program Files/Autodesk/Maya2019/plug-ins/camd/scripts;C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/scripts;C:/pipeline_modules/maya/ngSkinTools/1.7.9/scripts;C:/pipeline_modules/maya/pyIconTools/1.0/20XX/scripts;C:/pipeline_modules/maya/shard_matrix/1.0/20XX/scripts;C:/Allegorithmic/SubstanceMaya/2019/scripts;C:/Program Files/Autodesk/Bifrost/Maya2019/vnn/scripts;C:/Program Files/Autodesk/Maya2019/plug-ins/xgen/scripts;",
    "TT_PACKAGE": r"Maya",
    "SESSIONNAME": r"RDP-Tcp#114",
    "TT_PROJTYPE": r"Series",
    "ARNOLD_ROOT": r"C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/",
    "MAYA_RENDER_SETUP_GLOBAL_TEMPLATE_PATH": r"D:/Pipeline/paxtong/dev/git_repo/pipeline_monolith/config/LMM/RSTemplates",
    "PIPE_EXTERNAL": r"G:/Pipeline/pipeline_external",
    "TT_USER": r"paxtong",
    "LFX_PROJ": r"RCL",
    "MAYA_LOCATION": r"C:/Program Files/Autodesk/Maya2019",
    "QX_FLOATING_PORT": r"4567",
    "TT_VER": r"v0000",
    "RV_SHOTGUN_DEFAULT_SERVER_URL": r"https://icon.shotgunstudio.com",
    "TOONBOOM_LICENSE_FILE": r"2801@iconprfs02",
    "PIPE_BASE": r"D:/Pipeline/paxtong/dev/git_repo/pipeline_monolith",
    "PIPELINE_MODULES": r"C:/pipeline_modules",
    "RENDERMAN_ROOT": r"Z:/pipeline/pixar/RenderManStudio-19.0-maya2015",
    "USERDNSDOMAIN": r"ICON.LOCAL",
    "TT_STEPNAME": r"Rig",
    "ICON_SITE_CONFIG": r"v0002",
    "MAYA_SHELF_PATH": r"D:/Pipeline/paxtong/dev/git_repo/pipeline_monolith/maya/shelves",
    "TT_EPNAME": r"",
    "PIPENV_PYPI_MIRROR": r"http://devpi.icon.local:3141/icon/internal/+simple/",
    "ADSK_CLM_WPAD_PROXY_CHECK": r"FALSE",
    "MAYA_APP_DIR": r"C:/Users/paxtong/Documents/maya",
    "MAYA_PLUG_IN_RESOURCE_PATH": r";C:/Program Files/Autodesk/Maya2019/plug-ins/ATF/resources;C:/pipeline_modules/maya/AnimSchoolPicker/1.0/2019/resources;C:/Program Files/Autodesk/Bifrost/Maya2019/bifrost/resources;C:/pipeline_modules/maya/IconTools/1.1/2019/resources;C:/Program Files/Autodesk/Maya2019/plug-ins/MASH/resources;C:/pipeline_modules/maya/ornatrix/2.4.4.20888/resources;C:/pipeline_modules/maya/assetInfo/1.1/20XX/resources;C:/Program Files/Autodesk/Maya2019/plug-ins/fbx/resources;C:/pipeline_modules/maya/python_icon/1.0/20XX/resources;C:/Program Files/Autodesk/Maya2019/plug-ins/camd/resources;C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/resources;C:/pipeline_modules/maya/ngSkinTools/1.7.9/resources;C:/pipeline_modules/maya/pyIconTools/1.0/20XX/resources;C:/pipeline_modules/maya/shard_matrix/1.0/20XX/resources;C:/Allegorithmic/SubstanceMaya/2019/resources;C:/Program Files/Autodesk/Bifrost/Maya2019/vnn/resources;C:/Program Files/Autodesk/Maya2019/plug-ins/xgen/resources;",
    "RATTREE": r"Z:/pipeline/pixar/RenderManStudio-19.0-maya2015",
    "TT_ENTDESC": r"None",
    "TT_ASSTYPE": r"Character",
    "SUBSTANCE_PLUG_IN_PATH": r"C:/Allegorithmic/SubstanceMaya/2019/bin",
    "FULLNAME": r"Paxton Gerrish",
    "COMMONPROGRAMW6432": r"C:\Program Files\Common Files",
    "RIPRECISION": r"10",
    "XBMLANGPATH": r"D:/Pipeline/paxtong/dev/git_repo/pipeline_monolith/maya/icons;C:/Users/paxtong/Documents/maya/2019/prefs/icons;C:/Users/paxtong/Documents/maya/prefs/icons;C:/Program Files/Autodesk/Maya2019/icons;C:/Program Files/Autodesk/Maya2019/app-defaults;C:/Program Files/Autodesk/Maya2019/icons/paintEffects;C:/Program Files/Autodesk/Maya2019/icons/fluidEffects;C:/Program Files/Autodesk/Maya2019/icons/hair;C:/Program Files/Autodesk/Maya2019/icons/cloth;C:/Program Files/Autodesk/Maya2019/icons/live;C:/Program Files/Autodesk/Maya2019/icons/fur;C:/Program Files/Autodesk/Maya2019/icons/muscle;C:/Program Files/Autodesk/Maya2019/icons/turtle;C:/Program Files/Autodesk/Maya2019/icons/FBX;C:/Program Files/Autodesk/Maya2019/icons/mayaHIK;C:/Program Files/Autodesk/Maya2019/plug-ins/ATF/icons;C:/pipeline_modules/maya/AnimSchoolPicker/1.0/2019/icons;C:/Program Files/Autodesk/Bifrost/Maya2019/bifrost/icons;C:/pipeline_modules/maya/IconTools/1.1/2019/icons;C:/Program Files/Autodesk/Maya2019/plug-ins/MASH/icons;C:/pipeline_modules/maya/ornatrix/2.4.4.20888/icons;C:/pipeline_modules/maya/assetInfo/1.1/20XX/icons;C:/Program Files/Autodesk/Maya2019/plug-ins/fbx/icons;C:/pipeline_modules/maya/python_icon/1.0/20XX/icons;C:/Program Files/Autodesk/Maya2019/plug-ins/camd/icons;C:/pipeline_modules/solidangle/mtoa/3.3.0.2/2019/icons;C:/pipeline_modules/maya/ngSkinTools/1.7.9/icons;C:/pipeline_modules/maya/pyIconTools/1.0/20XX/icons;C:/pipeline_modules/maya/shard_matrix/1.0/20XX/icons;C:/Allegorithmic/SubstanceMaya/2019/icons;C:/Program Files/Autodesk/Bifrost/Maya2019/vnn/icons;C:/Program Files/Autodesk/Maya2019/plug-ins/xgen/icons",
}